### ISSUE TITLE
windows 环境下拉不下来代码

### ISSUE THREAD

**Issue by silencesama** [babyfish-ct/jimmer-examples#1]
win的文件名不能使用  : 这样的字符

[kotlin/:q!](https://github.com/babyfish-ct/jimmer-examples/blob/main/kotlin/%3Aq!)  这个文件名称非法了，建议改下文件名称

![image](https://github.com/babyfish-ct/jimmer-examples/assets/26505855/40af36e7-8fa6-4d54-88e5-28a7cbf1b180)

**Comment by babyfish-ct** [comment]
Fixed
