### ISSUE TITLE
《最简单的Repository》 章节代码有运行时异常

### ISSUE THREAD

**Issue by zengyufei** [babyfish-ct/jimmer-examples#4]
![image](https://github.com/user-attachments/assets/98f194f4-dbe3-4468-a06b-093cff1f5dec)

https://babyfish-ct.github.io/jimmer-doc/zh/docs/quick-view/fetch/feature#%E6%9C%80%E7%AE%80%E5%8D%95%E7%9A%84repository

快速预览 ★ > 1. 查询任意形状 > 功能介绍 > 最简单的Repository

这个章节里  BookRepository 有两个问题：

* @Repository 注解的 BookRepository 默认 final，导致 cglib 无法实现它的子类来实现动态代理，需要加入 open 关键字。
* @Repository 注解会导致 KSqlClient 无法注入，原因不明。

以上问题，直接把 @Repository 改成  @Component 就正常，也不需要 open 关键字。

**Comment by babyfish-ct** [comment]
spring-boot的kotlin插件负责自动open所有托管kotlin class. 这个细节我干下文档

**Comment by zengyufei** [comment]
***@***.***这个注解



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月31日(周四) 凌晨0:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [babyfish-ct/jimmer-examples] 《最简单的Repository》 章节代码有运行时异常 (Issue #4)




 
spring-boot的kotlin插件负责自动open所有托管kotlin class. 这个细节我干下文档

**Comment by zengyufei** [comment]
> spring-boot的kotlin插件负责自动open所有托管kotlin class. 这个细节我干下文档

Open不是问题，也不是最主要原因。是@Repo这个注解导致这一切事情发生。

**Comment by babyfish-ct** [comment]
![5c0c706ecdf834e55f324467016023ae](https://github.com/user-attachments/assets/a91d89d3-cebe-4418-9a68-64b89bef8439)

实际验证没问题，可启动，可运行。

下个版本，我会把所有kotlin例子都改成这种风格

**Comment by babyfish-ct** [comment]
对于spring-boot项目本，spring-boot整合了all open插件。但是对于独立的repository项目，需要引入all open插件，插件介绍https://kotlinlang.org/docs/all-open-plugin.html#gradle，当前场景应该配置为

```
allOpen {
	annotation("org.springframework.stereotype.Repository")
}
```

如果你这样做了，问题就解决了，这是是kotlin开发spring项目的的一个需要注意的点。

无论之前说的open问题，还是之后说的下个版本把所有kotlin例子都改成这个风格，都是这个意思。
